### ISSUE TITLE
comments while testing how to build my first python package

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/development#27]
Nice and simple guide to get started with python packages, thanks! :)

minor things:

- [x] Correct spelling "we finnish this section" at 3. First Module
- [x] `mkdir count_variants/cli count_variants/cli` should be `mkdir count_variants/cli count_variants/utils` at 3. First module
- [x] "modules in standard library follow" at 3. First module
- [x] there are 2 sections 3 on the page overview.md. Installing should be 4, right?

**Comment by moonso** [comment]
👍 👍 👍

**Comment by henrikstranneheim** [comment]
Done?

**Comment by northwestwitch** [comment]
I think so!
