### ISSUE TITLE
Describe how to phrase commit messages in git

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/development#33]
https://seesparkbox.com/foundry/semantic_commit_messages

https://kapeli.com/cheat_sheets/Semantic_Commits.docset/Contents/Resources/Documents/index

it's like writing commit messages: I want something that gives me rules like you might find on commit messages.

e.g. these are the rules of thumb I'm using
1. use present tense verb. The description of the commit message should be formulated according to: After applying this commit, you will have that functionality. Not: I have finished this work.
2. start your commit message with that verb
3. e.g.
  -  "Add description on commit messages"
  - "Fix #64"
  - "Remove description commit messages"

**Comment by ingkebil** [comment]
https://americanexpress.io/on-the-importance-of-commit-messages/
