### ISSUE TITLE
Describe how to install new tools for production

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/development#62]
Most of CG tools are installed via pip bash scripts (e.g. MIP). MIP has it figured how to properly do this, and other tools are doing this through pip. And given that we already have conventions inplace for conda environments, python packaging, bash aliases, etc; I propose to write a guide on how to install a new tool in our production setting.

I think this new document should at least address the following or at least point towards the relevant document:
- [ ] Updating .bashrc and relevant documents (link to document)
- [ ] Location for the source code, if necessary (e.g. microsalt it is $HOME)
- [ ] Conda env convention (link to document )
- [ ] Where to put/find necessary files (e.g. genome references data, third-party databases, etc). Currently it is in ..proj/bioinfo/...

**Comment by patrikgrenfeldt** [comment]
I suggest also adding two installation/update scripts in servers/resources/ called update-mytool-stage.sh and one called update-mytool-prod.sh so that the installation becomes a one-liner and reducing the need to know stuff on how to install to a minimum

**Comment by ingkebil** [comment]
Described here: https://github.com/Clinical-Genomics/development/blob/master/development/stage.md


Document location is confusing tho! There is a US about the need to refactor documentation [Zube #1800](https://zube.io/clinical-genomics/pbl-team-lessteamnamegreater/c/1800)
