### ISSUE TITLE
Create documentation on how to use up and us to activate prod/stage environments/ create the us function

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/development#68]
**Contact person:** KB and ES

**Problem:** We have a very nice way of sourcing everything we need for production using "up" but we don't have it written down how to use it. We want the same function for stage using "us".

**Suggested solution:** us and up documentation done in Development manual.

**Questions:**
Q1: Is us implemented?
A1: Yes!

**Comment by ingkebil** [comment]
Fixed in 459685a09fedfad6cae59f45470fc3fb20708d61
